import time

class Block:
    # Constructor for a new block. Takes the following parameters:
    # block_data: the transaction data to be stored in the block.
    # poet: the hash of [prev_block_hash + block_data + merkle_root] generated by the winner via Proof of Elapsed Time.
    #
    # A timestamp is autogenerated, and a merkle tree hash is also computed upon Block construction.

    def __init__(self, data: str, poet: str, prevhash = ""):
        self.timestamp = int(time.time()) 
        self.prevhash = prevhash
        self.data = data 
        self.poet = poet      
    
# A basic genesis block which all chains start from.
def Genesis():
    return Block("", "")