import time

class Block:
    # Constructor for a new block
    # Takes the following parameters:
    # data: the transaction data to be stored in the block
    # poet: the hash of [prev_block_hash + data + merkle_root] generated by the winner via Proof of Elapsed Time
    # A timestamp is autogenerated

    def __init__(self, data: str, poet: str, prevhash = ""):
        self.timestamp = int(time.time()) 
        self.prevhash = prevhash
        self.data = data 
        self.poet = poet      
    
# The genesis block from which all chains originate
def Genesis():
    return Block("", "")